# version 0.1

FROM ubuntu:18.04

# install nginx
# install uwsgi
# install python3
# install necessary packages
# create working directory
# copy code

RUN apt-get update -y
RUN apt-get install -y nginx
# RUN ufw allow 'Nginx HTTP'
# 
# CMD ['systemctl', 'start', 'nginx']
